//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDAKhoaHTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDKDOAN
    {
        public int MaDK { get; set; }
        public Nullable<int> MaDA { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> MaL { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MaSV { get; set; }
    
        public virtual DANGKYDOAN DANGKYDOAN { get; set; }
        public virtual DOAN DOAN { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
