//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDAKhoaHTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUDE()
        {
            this.DOANs = new HashSet<DOAN>();
        }
    
        public int MaCD { get; set; }
        public string TenCD { get; set; }
        public Nullable<int> MaL { get; set; }
    
        public virtual LOAI LOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOAN> DOANs { get; set; }
    }
}
