//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDAKhoaHTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOAN()
        {
            this.CHITIETDKDOANs = new HashSet<CHITIETDKDOAN>();
        }
    
        public int MaDA { get; set; }
        public string TenDA { get; set; }
        public string MoTa { get; set; }
        public string Anhbia { get; set; }
        public Nullable<System.DateTime> NgayNop { get; set; }
        public Nullable<int> MaL { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> MaGV { get; set; }
        public Nullable<bool> DaNopBaoCao { get; set; }
    
        public virtual CHUDE CHUDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDKDOAN> CHITIETDKDOANs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual NHOM NHOM { get; set; }
    }
}
