//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDAKhoaHTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        public int MaLop { get; set; }
        public Nullable<int> MaKhoaHoc { get; set; }
        public Nullable<int> MaHDT { get; set; }
        public string TenLop { get; set; }
    }
}
