//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLDAKhoaHTTT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.CHITIETDKDOANs = new HashSet<CHITIETDKDOAN>();
        }
    
        public string MaSV { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string DiaChiSV { get; set; }
        public string SDTsv { get; set; }
        public Nullable<System.DateTime> NgaySinhSV { get; set; }
        public Nullable<int> MaNhom { get; set; }
        public Nullable<int> MaTK { get; set; }
    
        public virtual NHOM NHOM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDKDOAN> CHITIETDKDOANs { get; set; }
        public virtual User User { get; set; }
    }
}
